version: '3.8'

services:
   jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped




  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: ordersuser
      POSTGRES_PASSWORD: orderspass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./order-system
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./order-system:/code
    ports:
      - "8000:8000"
    env_file:
      - ./order-system/.env.backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
        - REACT_APP_API_URL=http://web:8000/api

    depends_on:
      - web

volumes:
  postgres-data:
  jenkins_home:
